name: 'fast_sap_dw'
version: '1.0.0'
config-version: 2

profile: 'fast_sap_dw'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  fast_sap_dw:
    bronze:
      +materialized: view
    silver:
      +materialized: table
    gold:
      +materialized: table
